### ISSUE TITLE
다음 게시물로 넘어가지 않는 문제

### ISSUE THREAD

**Issue by SOMJANG** [SOMJANG/Instagram_Crawler#4]
#### 2022년 2월 3일 메일 문의
- 다음 게시물로 넘어가지 않는다
- 100초를 기다려도 넘어가지 않고 종료된다

**Comment by SOMJANG** [comment]
#### 2022년 2월 5일 확인 결과
- 인스타그램 페이지 구조 변경으로 인하여 기존에 css_selector에 넣어 다음 페이지로 넘어가는 버튼을 찾는데 사용하던 class 명 사용 불가

**Comment by SOMJANG** [comment]
### 변경된 class 명
- 기존 : "._65Bje.coreSpriteRightPaginationArrow"
- 변경 : ".wpO6b  "

### 변경 후 테스트 결과
```Bash
Message: element click intercepted: Element <button class="wpO6b ZQScA " type="button">...</button> is not clickable at point (917, 30). Other element would receive the click: <div class="RnEpo   _Yhr4     " role="presentation">...</div>
  (Session info: chrome=98.0.4758.80)

Traceback (most recent call last):
  File "<ipython-input-16-84e29c819442>", line 307, in extract_insta_data
    next_arrow_btn.click()
  File "/Users/donghyunjang/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/donghyunjang/anaconda3/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="wpO6b ZQScA " type="button">...</button> is not clickable at point (917, 30). Other element would receive the click: <div class="RnEpo   _Yhr4     " role="presentation">...</div>
  (Session info: chrome=98.0.4758.80)
```

위와 같은 에러 발생

**Comment by SOMJANG** [comment]
### 원인
- div 가 한 겹 감싸고 있어 바로 클릭 불가

### 해결
- css_selector 에서 사용하는 값 ".wpO6b " 에서 "div.l8mY4.feth3 > .wpO6b  " 로 변경
- .click() 대신 .send_keys(Keys.ENTER) 사용
   ```Python3
   from selenium.webdriver.common.keys import Keys
   WebDriverWait(driver, 100).until(EC.presence_of_element_located((By.CSS_SELECTOR, next_arrow_btn_css1)))
  time.sleep(5.0)
  next_arrow_btn = driver.find_element_by_css_selector(next_arrow_btn_css1)
   next_arrow_btn.send_keys(Keys.ENTER)
   ```
